### ISSUE TITLE
Can we pay electricity bill in installments?

### ISSUE THREAD

**Issue by ibenstokes** [ahmedasif1/bill-downloader#26]
However installments can be given on arrears of [electricity](https://fescoonlinebillcheck.pk/) dues outstanding against the consumer and whenever electricity dues are allowed to be paid in installments, interest is charged at the prevailing bank rates. In case of general connections for arrears amounting to Rs. 2,000.

**Comment by ahmedasif1** [comment]
This project downloads bill only. It does not help in paying it
